/**
 * Type generation — converts the tool registry catalog into TypeScript
 * declaration files for sandbox preload.
 *
 * Output layout (written to `typesDir`):
 *   <server>.d.ts         — per-server namespace with Input/Output interfaces
 *   <server>.routing.json — per-tool routing decisions for X1 adapter (Agent H)
 *   _index.d.ts           — combined ambient `declare global { namespace mcp.tools }` block
 *
 * Plan amendments (consolidated plan §3 Part B):
 *   1. Emit `@example` JSDoc blocks from `ToolDefinition.examples[]`
 *   2. Write `<server>.routing.json` capturing per-tool routing decisions
 *      so Agent H (X1 passthrough adapter) can read it without re-parsing types
 *
 * @module registry/typegen
 */

import { compile } from 'json-schema-to-typescript';
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { ToolDefinition, JsonSchema } from './index.js';

// ─────────────────────────────────────────────────────────────────────────────
// Routing manifest (written as <server>.routing.json)
// ─────────────────────────────────────────────────────────────────────────────

export interface RoutingManifest {
  /** Server name */
  server: string;
  /** Epoch ms when this manifest was generated */
  generatedAt: number;
  /** Per-tool routing decisions (defaults to execute_code when unset) */
  tools: Record<string, 'passthrough' | 'execute_code' | 'hidden'>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Sanitise a name so it can be used as a TypeScript identifier. */
function toIdentifier(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

/** Escape text for safe embedding inside a JSDoc comment block. */
function escapeJsDoc(text: string): string {
  return text.replace(/\*\//g, '* /');
}

/**
 * Build a JSDoc comment block from a description and optional examples array.
 * Follows the Anthropic Tool Use Examples pattern (plan amendment).
 */
function buildJsDoc(description: string, examples?: ToolDefinition['examples']): string {
  const lines: string[] = ['/**'];

  if (description) {
    for (const line of description.split('\n')) {
      lines.push(` * ${escapeJsDoc(line)}`);
    }
  }

  if (examples && examples.length > 0) {
    lines.push(' *');
    for (const ex of examples) {
      if (ex.description) {
        lines.push(` * @example ${escapeJsDoc(ex.description)}`);
      } else {
        lines.push(' * @example');
      }
      lines.push(` * args: ${escapeJsDoc(JSON.stringify(ex.args))}`);
      lines.push(` * result: ${escapeJsDoc(JSON.stringify(ex.result))}`);
    }
  }

  lines.push(' */');
  return lines.join('\n');
}

/**
 * Attempt to compile a JSON Schema to a TypeScript type string via
 * json-schema-to-typescript.  On failure (e.g. recursive schema) falls
 * back to `type <Name> = unknown` — never crashes the generation run.
 * Per the kickoff doc: "if json-schema-to-typescript chokes on a recursive
 * schema, accept whatever it emits and move on".
 */
async function schemaToTs(schema: JsonSchema, name: string): Promise<string> {
  try {
    const result = await compile(schema as object, name, {
      bannerComment: '',
      unknownAny: false,
      strictIndexSignatures: false,
    });
    return result.trim();
  } catch {
    // Recursive or malformed schema — safe fallback
    return `export type ${toIdentifier(name)} = unknown; // schema could not be compiled`;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate the TypeScript declaration string for a single server's tools.
 * Returns a string suitable for writing to `<server>.d.ts`.
 */
export async function generateServerTypes(
  serverName: string,
  tools: ToolDefinition[]
): Promise<string> {
  const id = toIdentifier(serverName);
  const lines: string[] = [
    '// Auto-generated by MCP Conductor. Do not edit.',
    `// Source: ${serverName} tool catalog`,
    '',
    `export namespace ${id} {`,
  ];

  for (const tool of tools) {
    const toolId = toIdentifier(tool.name);

    // Input interface
    const inputSchema: JsonSchema =
      tool.inputSchema && Object.keys(tool.inputSchema).length > 0
        ? tool.inputSchema
        : { type: 'object' };

    const inputTypeName = `${toolId}_Input`;
    const inputTs = await schemaToTs(inputSchema, inputTypeName);

    lines.push('');
    // Emit JSDoc with @example blocks (plan amendment #1)
    lines.push(
      buildJsDoc(tool.description, tool.examples)
        .split('\n')
        .map((l) => `  ${l}`)
        .join('\n')
    );
    lines.push(
      inputTs
        .split('\n')
        .map((l) => `  ${l}`)
        .join('\n')
    );

    // Output interface (optional)
    if (tool.outputSchema && Object.keys(tool.outputSchema).length > 0) {
      const outputTypeName = `${toolId}_Output`;
      const outputTs = await schemaToTs(tool.outputSchema, outputTypeName);
      lines.push('');
      lines.push(
        outputTs
          .split('\n')
          .map((l) => `  ${l}`)
          .join('\n')
      );
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate the combined `_index.d.ts` that exposes `mcp.tools` as a global
 * ambient namespace, referencing each per-server namespace.
 */
export function generateIndexTypes(serverNames: string[]): string {
  const lines: string[] = ['// Auto-generated by MCP Conductor. Do not edit.', ''];

  for (const name of serverNames) {
    const id = toIdentifier(name);
    lines.push(`import type { ${id} } from './${name}.js';`);
  }

  lines.push('');
  lines.push('declare global {');
  lines.push('  namespace mcp {');
  lines.push('    namespace tools {');

  for (const name of serverNames) {
    const id = toIdentifier(name);
    lines.push(`      const ${id}: {`);
    lines.push(`        [tool: string]: (args: unknown) => Promise<unknown>;`);
    lines.push(`      } & typeof import('./${name}.js').${id};`);
  }

  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('export {};');
  lines.push('');

  return lines.join('\n');
}

/**
 * Build the routing manifest for a server (plan amendment #2).
 * Defaults to `execute_code` when `tool.routing` is not set, preserving
 * current behaviour for all existing tools.
 */
export function buildRoutingManifest(
  serverName: string,
  tools: ToolDefinition[]
): RoutingManifest {
  const toolRoutes: Record<string, 'passthrough' | 'execute_code' | 'hidden'> = {};

  for (const tool of tools) {
    toolRoutes[tool.name] = tool.routing ?? 'execute_code';
  }

  return {
    server: serverName,
    generatedAt: Date.now(),
    tools: toolRoutes,
  };
}

/**
 * Write all type and routing files to `typesDir`.
 * Creates the directory if it does not exist.
 * Returns the list of written file paths.
 */
export async function writeTypesToDir(
  typesDir: string,
  toolsByServer: Map<string, ToolDefinition[]>
): Promise<string[]> {
  await mkdir(typesDir, { recursive: true });

  const written: string[] = [];
  const serverNames: string[] = [];

  for (const [serverName, tools] of toolsByServer) {
    serverNames.push(serverName);

    // <server>.d.ts
    const dtsContent = await generateServerTypes(serverName, tools);
    const dtsPath = join(typesDir, `${serverName}.d.ts`);
    await writeFile(dtsPath, dtsContent, 'utf8');
    written.push(dtsPath);

    // <server>.routing.json  (plan amendment for X1 adapter — Agent H)
    const manifest = buildRoutingManifest(serverName, tools);
    const routingPath = join(typesDir, `${serverName}.routing.json`);
    await writeFile(routingPath, JSON.stringify(manifest, null, 2), 'utf8');
    written.push(routingPath);
  }

  // _index.d.ts
  const indexContent = generateIndexTypes(serverNames);
  const indexPath = join(typesDir, '_index.d.ts');
  await writeFile(indexPath, indexContent, 'utf8');
  written.push(indexPath);

  return written;
}
